config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => "/ckeditor"
  get  "/signup", to: "users#new"
  post "/signup", to: "users#create"
  get  "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  resources :users do
    resources :following, only: :index
    resources :followers, only: :index
  end
  resources :account_activations, only: :edit
  resources :books
  resources :categories
  resources :ratings, only: :update
  resources :relationships, only: %i(create destroy)

  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#home"
  end
end

app/views/shared/_book_form.html.erb
<%= form_for @book do |f| %>
  <%= render "shared/error_messages", object: f.object %>
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :name %>
    <%= f.label :description %>
    <%= f.cktext_area :description, rows: 10 %>
  </div>
  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
  <span class="picture">
    <%= f.file_field :picture, accept: "image/jpeg,image/gif,image/png" %>
  </span>
<% end %>

<script type="text/javascript">
  $("#book_picture").bind("change", function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert("Maximum file size is 5MB. Please choose a smaller file.");
    }
  });
</script>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <%= t(".form_contains", count: pluralize(@user.errors.count, t(".error"))) %>
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= user_following_index_path @user %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    <%= t ".following" %>
  </a>
  <a href="<%= user_followers_path @user %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    <%= t ".followers" %>
  </a>
</div>

app/views/shared/show_follow.html.erb
<% provide :title, @title %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <%= gravatar_for @user %>
      <h1><%= @user.name %></h1>
      <span><%= link_to t(".view_my_profile"), @user %></span>
      <span><b><%= t ".book" %></b> <%= @user.books.count %></span>
    </section>
    <section class="stats">
      <%= render "shared/stats" %>
      <% if @users.any? %>
        <div class="user_avatars">
          <% @users.each do |user| %>
            <%= link_to gravatar_for(user, size: 30), user %>
          <% end %>
        </div>
      <% end %>
    </section>
  </aside>
  <div class="col-md-8">
    <h3><%= @title %></h3>
    <% if @users.any? %>
      <ul class="users follow">
        <%= render @users %>
      </ul>
      <%= will_paginate %>
    <% end %>
  </div>
</div>