config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => "/ckeditor"
  get  "/signup", to: "users#new"
  post "/signup", to: "users#create"
  get  "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  resources :users do
    resources :following, only: :index
    resources :followers, only: :index
  end
  resources :account_activations, only: :edit
  resources :books
  resources :categories
  resources :ratings, only: :update
  resources :relationships, only: %i(create destroy)

  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#home"
  end
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_one :source, dependent: :destroy
  has_many :ratings, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :book_categories
  has_many :categories, through: :book_categories
  has_many :book_authors
  has_many :author, through: :book_authors
  default_scope -> { order(created_at: :desc) }
  mount_uploader :picture, PictureUploader
  validates :user_id, presence: true
  validates :description, presence: true, length: {maximum: 800}
  validate :picture_size

  scope :recently_published, -> { order(created_at: :desc).limit 6 }
  scope :find_feed, ->(following_ids){where user_id: following_ids}

  def average_rating
    return 0 if ratings.blank?
    ratings.sum(:score) / ratings.size
  end

  private

  # Validates the size of an uploaded picture.
  def picture_size
    if picture.size > 5.megabytes
      errors.add(:picture, "should be less than 5MB")
    end
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :logged_in_user
  before_action :correct_user, only: %i(edit update destroy)

  def index
    @books = Book.find_feed(current_user.following_ids << current_user.id).paginate page: params[:page]
  end

  def show
    @book = Book.find_by id: params[:id]
    if @book.nil?
      flash[:info] = t ".flash_info"
      redirect_to root_url
    else
      @user = @book.user
    end
    @rating = current_user.ratings.find_or_initialize_by book_id: @book.id
  end

  def new
    @book = current_user.books.build
  end

  def create
    @book = current_user.books.build book_params
    if @book.save
      flash[:success] = t ".flash_success"
      redirect_to root_url
    else
      render "static_pages/home"
    end
  end

  def edit
  end

  def update
    if book.update_attributes book_params
      flash[:success] = t ".flash_success"
      redirect_to book
    else
      render :edit
    end
  end

  def destroy
    book.destroy
    flash[:success] = t ".flash_success"
    redirect_back fallback_location: root_url
  end

  private

  attr_reader :book

  def book_params
    params.require(:book).permit :name, :description, :picture, category_ids: []
  end

  def correct_user
    @book = current_user.books.find_by id: params[:id]
    redirect_to root_url if book.nil?
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_book.html.erb
<div class="card">
  <div class="row">
    <div class="col-md-5 wrapthumbnail">
      <a href="#">
        <% if book.picture? %>
          <div class="thumbnail" style="background-image:url(<%= book.picture.url %>);">
          </div>
        <% end %>
      </a>
    </div>
    <div class="col-md-7">
      <div class="card-block">
        <h2 class="card-title"><%= link_to book.name, book_path(book)%></h2>
        <h4 class="card-text">
          <%= sanitize book.description %>
        </h4>
        <div class="metafooter">
          <div class="wrapfooter">
            <span class="meta-footer-thumb">
              <%= link_to gravatar_for(book.user, size: 50,
                alt: book.user.name), book.user %>
            </span>
            <span class="author-meta">
              <span class="post-name">
                <%= link_to book.user.name, book.user %>
              </span>
              <br/>
              <span class="post-date">
                <%= book.created_at.strftime("%d %b %Y") %>
                <% if current_user?(book.user) %>
                  <span class="dot"></span>
                  <%= link_to t(".edit"), edit_book_path(book) %>
                  <span class="dot"></span>
                  <%= link_to t(".delete"), book, method: :delete,
                    data: { confirm: t(".destroy_confirm") } %>
                <% end %>
              </span>
            </span>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/books/_form.html.erb
<%= form_for @book do |f| %>
  <%= render "shared/error_messages", object: f.object %>
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :name %>
    <%= f.label :description %>
    <%= f.cktext_area :description, rows: 10 %>
    <%= f.label :categories %>
    <ul class="book_form">
      <%= collection_check_boxes(:book, :category_ids, Category.all, :id, :name) do |category| %>
        <li>
          <%= category.label("data-value": category.value) { category.check_box + category.text }%>
        </li>
      <% end %>
    </ul>
    <%= f.label :authors %>
    <ul class="book_form">
      <%= collection_check_boxes(:book, :author_ids, Author.all, :id, :name) do |author| %>
        <li>
          <%= author.label("data-value": author.value) { author.check_box + author.text }%>
        </li>
      <% end %>
    </ul>
  </div>
  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
  <span class="picture">
    <%= f.file_field :picture, accept: "image/jpeg,image/gif,image/png" %>
  </span>
<% end %>

<script type="text/javascript">
  $("#book_picture").bind("change", function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert("Maximum file size is 5MB. Please choose a smaller file.");
    }
  });
</script>

app/views/books/edit.html.erb
<% provide :title, t(".title") %>
<% provide :button_text, t(".save_changes") %>
<h1><%= t ".update_book" %></h1>
<div class="row">
  <div class="col-md-6 offset-md-3">
    <%= render "form" %>
  </div>
</div>

app/views/books/index.html.erb
<% provide :title, t(".title") %>
<h1><%= t ".title" %></h1>

<div class="card-columns listfeaturedtag">
  <%= render @books %>
</div>

<%= will_paginate @books,
  renderer: WillPaginate::ActionView::Bootstrap4LinkRenderer,
  class: "justify-content-center" %>

app/views/books/new.html.erb
<% provide :button_text, t(".publish") %>
<%= render "form" %>

app/views/books/show.html.erb
<% provide :title, @book.name %>
<link href="https://fonts.googleapis.com/css?family=Righteous%7CMerriweather:300,300i,400,400i,700,700i" rel="stylesheet">

<!-- Begin Article
================================================== -->
<div class="container">
  <div class="row">

    <!-- Begin Fixed Left Share -->
    <div class="col-md-2 col-xs-12">
      <div class="share">
        <p><%= t ".share" %></p>
        <ul>
          <li>
            <a target="_blank" href="#">
              <svg class="svgIcon-use" width="29" height="29" viewbox="0 0 29 29">
                <path d="M21.967 11.8c.018 5.93-4.607 11.18-11.177 11.18-2.172 0-4.25-.62-6.047-1.76l-.268.422-.038.5.186.013.168.012c.3.02.44.032.6.046 2.06-.026 3.95-.686 5.49-1.86l1.12-.85-1.4-.048c-1.57-.055-2.92-1.08-3.36-2.51l-.48.146-.05.5c.22.03.48.05.75.08.48-.02.87-.07 1.25-.15l2.33-.49-2.32-.49c-1.68-.35-2.91-1.83-2.91-3.55 0-.05 0-.01-.01.03l-.49-.1-.25.44c.63.36 1.35.57 2.07.58l1.7.04L7.4 13c-.978-.662-1.59-1.79-1.618-3.047a4.08 4.08 0 0 1 .524-1.8l-.825.07a12.188 12.188 0 0 0 8.81 4.515l.59.033-.06-.59v-.02c-.05-.43-.06-.63-.06-.87a3.617 3.617 0 0 1 6.27-2.45l.2.21.28-.06c1.01-.22 1.94-.59 2.73-1.09l-.75-.56c-.1.36-.04.89.12 1.36.23.68.58 1.13 1.17.85l-.21-.45-.42-.27c-.52.8-1.17 1.48-1.92 2L22 11l.016.28c.013.2.014.35 0 .52v.04zm.998.038c.018-.22.017-.417 0-.66l-.498.034.284.41a8.183 8.183 0 0 0 2.2-2.267l.97-1.48-1.6.755c.17-.08.3-.02.34.03a.914.914 0 0 1-.13-.292c-.1-.297-.13-.64-.1-.766l.36-1.254-1.1.695c-.69.438-1.51.764-2.41.963l.48.15a4.574 4.574 0 0 0-3.38-1.484 4.616 4.616 0 0 0-4.61 4.613c0 .29.02.51.08.984l.01.02.5-.06.03-.5c-3.17-.18-6.1-1.7-8.08-4.15l-.48-.56-.36.64c-.39.69-.62 1.48-.65 2.28.04 1.61.81 3.04 2.06 3.88l.3-.92c-.55-.02-1.11-.17-1.6-.45l-.59-.34-.14.67c-.02.08-.02.16 0 .24-.01 2.12 1.55 4.01 3.69 4.46l.1-.49-.1-.49c-.33.07-.67.12-1.03.14-.18-.02-.43-.05-.64-.07l-.76-.09.23.73c.57 1.84 2.29 3.14 4.28 3.21l-.28-.89a8.252 8.252 0 0 1-4.85 1.66c-.12-.01-.26-.02-.56-.05l-.17-.01-.18-.01L2.53 21l1.694 1.07a12.233 12.233 0 0 0 6.58 1.917c7.156 0 12.2-5.73 12.18-12.18l-.002.04z"></path>
              </svg>
            </a>
          </li>
          <li>
            <a target="_blank" href="#">
              <svg class="svgIcon-use" width="29" height="29" viewbox="0 0 29 29">
                <path d="M16.39 23.61v-5.808h1.846a.55.55 0 0 0 .546-.48l.36-2.797a.551.551 0 0 0-.547-.62H16.39V12.67c0-.67.12-.813.828-.813h1.474a.55.55 0 0 0 .55-.55V8.803a.55.55 0 0 0-.477-.545c-.436-.06-1.36-.116-2.22-.116-2.5 0-4.13 1.62-4.13 4.248v1.513H10.56a.551.551 0 0 0-.55.55v2.797c0 .304.248.55.55.55h1.855v5.76c-4.172-.96-7.215-4.7-7.215-9.1 0-5.17 4.17-9.36 9.31-9.36 5.14 0 9.31 4.19 9.31 9.36 0 4.48-3.155 8.27-7.43 9.15M14.51 4C8.76 4 4.1 8.684 4.1 14.46c0 5.162 3.75 9.523 8.778 10.32a.55.55 0 0 0 .637-.543v-6.985a.551.551 0 0 0-.55-.55H11.11v-1.697h1.855a.55.55 0 0 0 .55-.55v-2.063c0-2.02 1.136-3.148 3.03-3.148.567 0 1.156.027 1.597.06v1.453h-.924c-1.363 0-1.93.675-1.93 1.912v1.78c0 .3.247.55.55.55h2.132l-.218 1.69H15.84c-.305 0-.55.24-.55.55v7.02c0 .33.293.59.623.54 5.135-.7 9.007-5.11 9.007-10.36C24.92 8.68 20.26 4 14.51 4"></path>
              </svg>
            </a>
          </li>
        </ul>
        <div class="sep">
        </div>
        <p><%= t ".comment" %></p>
        <ul>
          <li>
            <a href="#comments">
              42<br/>
              <svg class="svgIcon-use" width="29" height="29" viewbox="0 0 29 29"><path d="M21.27 20.058c1.89-1.826 2.754-4.17 2.754-6.674C24.024 8.21 19.67 4 14.1 4 8.53 4 4 8.21 4 13.384c0 5.175 4.53 9.385 10.1 9.385 1.007 0 2-.14 2.95-.41.285.25.592.49.918.7 1.306.87 2.716 1.31 4.19 1.31.276-.01.494-.14.6-.36a.625.625 0 0 0-.052-.65c-.61-.84-1.042-1.71-1.282-2.58a5.417 5.417 0 0 1-.154-.75zm-3.85 1.324l-.083-.28-.388.12a9.72 9.72 0 0 1-2.85.424c-4.96 0-8.99-3.706-8.99-8.262 0-4.556 4.03-8.263 8.99-8.263 4.95 0 8.77 3.71 8.77 8.27 0 2.25-.75 4.35-2.5 5.92l-.24.21v.32c0 .07 0 .19.02.37.03.29.1.6.19.92.19.7.49 1.4.89 2.08-.93-.14-1.83-.49-2.67-1.06-.34-.22-.88-.48-1.16-.74z"></path></svg>
            </a>
          </li>
        </ul>
      </div>
    </div>
    <!-- End Fixed Left Share -->

    <!-- Begin Post -->
    <div class="col-md-8 col-md-offset-2 col-xs-12">
      <div class="mainheading">

        <!-- Begin Top Meta -->
        <div class="row post-top-meta">
          <div class="col-md-2">
            <%= link_to gravatar_for(@user, size: 50, alt: @user.name), @user %>
          </div>
          <div class="col-md-10">
            <%= link_to @user.name, @user, class: "link-dark" %>
            <span id="follow_form">
              <%= render "users/follow_form" if logged_in? %>
            </span>
            <span class="author-description">
              <%= t ".dummy_description" %>
            </span>
            <span class="post-date">
              <%= t ".publised_at" %> <%= @book.created_at.strftime("%d %b %Y") %>
            </span>
            <% unless @book.created_at == @book.updated_at %>
              <span class="dot"></span>
              <span class="post-date">
                <%= t ".updated_at" %> <%= @book.updated_at.strftime("%d %b %Y") %>
              </span>
            <% end %>
            <% if current_user == @book.user %>
              <span class="dot"></span>
              <span class="post-date">
                <%= link_to t(".edit"), edit_book_path %>
              </span>
              <span class="dot"></span>
              <span class="post-date">
                <%= link_to t(".delete"), @book, method: :delete,
                  data: { confirm: t(".delete_confirm") } %>
              </span>
            <% end %>
            <br>
            <span class="post-date">
               <strong><%= t ".average_rating" %></strong>
               <span id="star" data=<%= @book.average_rating %>></span>
            </span>
            <br>
            <span class="post-date">
               <strong><%= t ".your_rating" %></strong>
               <span id="user_star" data-id=<%= @rating.id.to_i %> data-score=<%= @rating.score %> data-book-id=<%= @book.id %>></span>
            </span>
          </div>
        </div>
        <!-- End Top Menta -->

        <h1 class="posttitle"><%= @book.name %></h1>

      </div>

      <!-- Begin Featured Image -->
      <% if @book.picture? %>
        <%= image_tag (@book.picture.url), class: "featured-image img-fluid" %>
      <% end %>
      <!-- End Featured Image -->

      <!-- Begin Post Content -->
      <div class="article-post">
        <%= sanitize @book.description %>
      </div>
      <!-- End Post Content -->

      <!-- Begin Tags -->
      <div class="after-post-tags">
        <ul class="tags">
          <% @book.categories.each do |category| %>
            <li><%= link_to category.name, category_path(category) %></li>
          <% end %>
        </ul>
      </div>
      <!-- End Tags -->

    </div>
    <!-- End Post -->

  </div>
</div>
<!-- End Article
================================================== -->

<div class="hideshare"></div>

<!-- Begin Related
================================================== -->
<div class="graybg">
  <div class="container">
    <div class="row listrecent listrelated">

      <!-- begin post -->
      <div class="col-md-4">
        <div class="card">
          <a href="post.html">
            <%= image_tag("/assets/demopic/9.jpg",
              class: "img-fluid img-thumb") %>
          </a>
          <div class="card-block">
            <h2 class="card-title">
              <a href="post.html"><%= t ".dummy_related_title" %></a>
            </h2>
            <div class="metafooter">
              <div class="wrapfooter">
                <span class="meta-footer-thumb">
                  <%= link_to gravatar_for(@user, size: 50, alt: @user.name),
                    @user %>
                </span>
                <span class="author-meta">
                  <span class="post-name">
                    <%= link_to @user.name, @user %>
                  </span>
                  <br/>
                  <span class="post-date">
                    <%= @book.created_at.strftime("%d %b %Y") %>
                  </span>
                </span>
              </div>
            </div>
          </div>
        </div>
      </div>
      <!-- end post -->

      <!-- begin post -->
      <div class="col-md-4">
        <div class="card">
          <a href="post.html">
            <%= image_tag("/assets/demopic/8.jpg",
              class: "img-fluid img-thumb") %>
          </a>
          <div class="card-block">
            <h2 class="card-title">
              <a href="post.html"><%= t ".dummy_related_title" %></a>
            </h2>
            <div class="metafooter">
              <div class="wrapfooter">
                <span class="meta-footer-thumb">
                  <%= link_to gravatar_for(@user, size: 50, alt: @user.name),
                    @user %>
                </span>
                <span class="author-meta">
                  <span class="post-name">
                    <%= link_to @user.name, @user %>
                  </span>
                  <br/>
                  <span class="post-date">
                    <%= @book.created_at.strftime("%d %b %Y") %>
                  </span>
                </span>
              </div>
            </div>
          </div>
        </div>
      </div>
      <!-- end post -->

      <!-- begin post -->
      <div class="col-md-4">
        <div class="card">
          <a href="post.html">
            <%= image_tag("/assets/demopic/7.jpg",
              class: "img-fluid img-thumb") %>
          </a>
          <div class="card-block">
            <h2 class="card-title">
              <a href="post.html"><%= t ".dummy_related_title" %></a>
            </h2>
            <div class="metafooter">
              <div class="wrapfooter">
                <span class="meta-footer-thumb">
                  <%= link_to gravatar_for(@user, size: 50, alt: @user.name),
                    @user %>
                </span>
                <span class="author-meta">
                  <span class="post-name">
                    <%= link_to @user.name, @user %>
                  </span>
                  <br/>
                  <span class="post-date">
                    <%= @book.created_at.strftime("%d %b %Y") %>
                  </span>
                </span>
              </div>
            </div>
          </div>
        </div>
      </div>
      <!-- end post -->

    </div>
  </div>
</div>
<!-- End Related Posts
================================================== -->