config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => "/ckeditor"
  get  "/signup", to: "users#new"
  post "/signup", to: "users#create"
  get  "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  resources :users do
    resources :following, only: :index
    resources :followers, only: :index
  end
  resources :account_activations, only: :edit
  resources :books
  resources :categories
  resources :ratings, only: :update
  resources :relationships, only: %i(create destroy)

  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#home"
  end
end

app/views/layouts/_footer.html.erb
<div class="footer">
  <p class="pull-left"><%= t(".copyright", year: Time.now.year).html_safe %></p>
  <p class="pull-right">
    <%= t(".theme_by", link: "https://www.facebook.com/manhcuongdtbk",
      author: "manhcuongdtbk").html_safe %>
  </p>
  <div class="clearfix">
  </div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-white fixed-top mediumnavigation">
<button class="navbar-toggler navbar-toggler-right"
  type="button" data-toggle="collapse" data-target="#navbarsExampleDefault"
  aria-controls="navbarsExampleDefault" aria-expanded="false"
  aria-label="Toggle navigation">
<span class="navbar-toggler-icon"></span>
</button>
<div class="container">
  <!-- Begin Logo -->
  <%= link_to image_tag("logo.png", alt: "Logo"), root_path,
    class: "navbar-brand" %>
  <!-- End Logo -->
  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <!-- Begin Menu -->
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <%= link_to t(".home"), root_path, class: "nav-link" %>
      </li>
      <% if logged_in? %>
        <li class="nav-item">
          <%= link_to t(".users"), users_path, class: "nav-link" %>
        </li>
        <li class="dropdown nav-item">
          <a href="#" class="dropdown-toggle nav-link" data-toggle="dropdown">
            <%= t ".books" %> <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li class="dropdown-item">
              <%= link_to t(".all_books"), books_path, class: "nav-link" %>
            </li>
            <li class="dropdown-item">
              <%= link_to t(".upload_book"), new_book_path, class: "nav-link" %>
            </li>
          </ul>
        </li>
        <li class="nav-item">
          <%= link_to t(".categories"), categories_path, class: "nav-link" %>
        </li>
        <li class="dropdown nav-item">
          <a href="#" class="dropdown-toggle nav-link" data-toggle="dropdown">
            <%= t ".account" %> <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li class="dropdown-item">
              <%= link_to t(".profile"), current_user, class: "nav-link" %>
            </li>
            <li class="dropdown-item">
              <%= link_to t(".settings"), edit_user_path(current_user),
                class: "nav-link" %>
            </li>
            <li class="dropdown-divider"></li>
            <li class="dropdown-item">
              <%= link_to t(".logout"), logout_path, method: :delete,
                class: "nav-link" %>
            </li>
          </ul>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to t(".login"), login_path, class: "nav-link" %>
        </li>
      <% end %>
      <li class="dropdown nav-item">
        <a href="#" class="nav-link" data-toggle="dropdown">
          <i class="fa fa-globe" aria-hidden="true"></i></b>
        </a>
        <ul class="dropdown-menu">
          <li class="dropdown-item">
            <%= link_to t(".english"), {locale:"en"}, {class: "nav-link"} %>
          </li>
          <li class="dropdown-item">
            <%= link_to t(".vietnamese"), {locale:"vi"}, {class: "nav-link"} %>
          </li>
        </ul>
      </li>
    </ul>
    <!-- End Menu -->
  </div>
</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css?family=Righteous" rel="stylesheet">
  </head>

  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render "layouts/footer" %>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
    </div>
  </body>
</html>